# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-23 17:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quoraapp', '0002_auto_20171123_1648'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='Question',
            new_name='question',
        ),
    ]
