# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-24 13:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quoraapp', '0004_auto_20171123_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='upvote',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
