# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-24 13:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quoraapp', '0005_upvote_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upvote',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
