# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-24 13:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quoraapp', '0006_auto_20171124_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upvote',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
